package algorithmTests;

/**
 * Not finished
 * 
 * @author <a href="https://github.com/probabilist-us">R. W. R. Darling</a>
 *
 */
public class TenPointLnkageTest {
	/**
	 * Minimal
	 */
	public TenPointLnkageTest() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * Not completed
	 * 
	 * @param args none
	 */
	public static void main(String[] args) {
		TenPointLnkageTest test = new TenPointLnkageTest();

	}

	/**
	 * Generated by rejection sampling 9 billion times from uniform random ranking
	 * systems on ten points, stopping at first 3-concordant one. Not concordant.
	 */
	public final int[][] tenPoint3CRankTable = new int[][] { { 0, 7, 6, 4, 8, 3, 1, 5, 9, 2 },
			{ 5, 0, 3, 6, 7, 8, 1, 4, 9, 2 }, { 7, 6, 0, 1, 9, 5, 3, 4, 8, 2 }, { 2, 9, 5, 0, 4, 6, 3, 8, 7, 1 },
			{ 9, 8, 7, 4, 0, 3, 6, 2, 1, 5 }, { 4, 9, 3, 6, 5, 0, 1, 7, 8, 2 }, { 1, 6, 5, 4, 8, 3, 0, 7, 9, 2 },
			{ 7, 9, 1, 8, 2, 3, 5, 0, 4, 6 }, { 9, 6, 7, 5, 1, 3, 8, 2, 0, 4 }, { 7, 5, 4, 2, 8, 3, 1, 6, 9, 0 } };

}
